game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

solve:
    path:     /solve/{card}
    defaults: { _controller: GameBundle:Default:solve, _format: json }
    methods: [POST]
    requirements:
        _format: json|js
        answer: '\w+'

listCard:
    path:     /card/list
    defaults: { _controller: GameBundle:Default:listCard }
